#!/usr/bin/env python3
"""Generate the ARTales brand board PNG preview as a local/workflow artifact.

The script intentionally writes to artifact-output/ by default so generated PNG
files are not committed to the repository.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import subprocess

DEFAULT_SOURCE = Path("brand/artales/overview/artales-brand-composite-board.v0.2.svg")
DEFAULT_OUTPUT_DIR = Path("artifact-output/artales-brand-board-preview/v0.2")
DEFAULT_PNG_NAME = "artales-brand-composite-board.v0.2.png"
DEFAULT_MANIFEST_NAME = "artales-brand-board-preview-manifest.v0.2.json"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_preview(source_svg: Path, output_dir: Path, scale: float) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_png = output_dir / DEFAULT_PNG_NAME
    manifest_path = output_dir / DEFAULT_MANIFEST_NAME
    readme_path = output_dir / "README.md"

    render_js = """
const sharp = require('sharp');
const [source, output, scaleValue] = process.argv.slice(1);
sharp(source, { density: 96 * Number(scaleValue) })
  .png()
  .toFile(output)
  .then(() => {})
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
"""
    subprocess.run(
        ["node", "-e", render_js, str(source_svg), str(output_png), str(scale)],
        check=True,
    )

    manifest = {
        "manifest_id": "artales-brand-board-preview-manifest.v0.2",
        "status": "generated_artifact_only_not_committed",
        "artifact_name": "artales-brand-board-preview-v0.2",
        "source_svg_path": str(source_svg),
        "output_png_path": str(output_png),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_svg_sha256": sha256_file(source_svg),
        "output_png_sha256": sha256_file(output_png),
        "runtimeImpact": False,
        "dbImpact": False,
        "envImpact": False,
        "notes": [
            "Generated by workflow_dispatch for human review only.",
            "The PNG is intentionally not committed in the Codex PR flow.",
            "The committed sources remain the SVG board, JSON metadata, registry, docs, and generator workflow.",
        ],
    }

    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    readme_path.write_text(
        "# ARTales Brand Board Preview v0.2\n\n"
        "This directory is generated by the manual GitHub Actions workflow "
        "`artales-generate-brand-board-preview.yml`.\n\n"
        "The PNG in this artifact is the canonical human review preview for "
        "ARTales Brand Snapshot v0.2. It is not committed to the repository "
        "because binary files are not supported in the Codex PR flow.\n\n"
        "Generated files:\n"
        f"- `{DEFAULT_PNG_NAME}`\n"
        f"- `{DEFAULT_MANIFEST_NAME}`\n",
        encoding="utf-8",
    )

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the ARTales v0.2 brand board PNG preview artifact.")
    parser.add_argument("--source-svg", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--scale", type=float, default=4 / 3)
    args = parser.parse_args()

    manifest = render_preview(args.source_svg, args.output_dir, args.scale)
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
